# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 21613
  #context-path: /springboot

# 日志配置
logging:
  file:
    max-history: 15
    name: /var/danastudio/log/datasource_pool/datasource_pool.log

# rsa 配置
rsa:
  enabled: true
  public-key: sad



datasource-list: druid
# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.facebook.presto.jdbc.PrestoDriver
    druid:
      url: jdbc:presto://192.168.90.46:9999/hive/odsdb?user=hive
      username:
      password:

      # 连接池配置
      initial-size: 1
      max-active: 10
      min-idle: 1
      filters: mergeStat
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          enabled: true
      #      # 监控配置
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin



##########################  mybatis   ##########################

mybatis:
  configuration:
    return-instance-for-empty-row: true
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml