# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  #context-path: /springboot

# 日志配置
logging:
  file:
    path: /var/danastudio/log
    max-history: 15

# rsa 配置
rsa:
  enabled: true
  public-key: sad



datasource-list: druid
# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.facebook.presto.jdbc.PrestoDriver
    druid:
      url: jdbc:presto://192.168.90.46:9999/hive/odsdb?user=hive
      username:
      password:

      # 连接池配置
      initial-size: 1
      max-active: 10
      min-idle: 1
      filters: stat,wall,config
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      # 检查池中的连接是否仍可用的 SQL 语句,druid会连接到数据库执行该SQL
      validation-query: select 1
      # 当程序请求连接，池在分配连接时，是否先检查该连接是否有效。(高效)
      test-while-idle: true
      # 申请连接时,进行连接有效性检查（低效，影响性能）
      test-on-borrow: false
      # 返还连接时,进行连接有效性检查（低效，影响性能）
      test-on-return: false
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*



##########################  mybatis   ##########################

mybatis:
  configuration:
    return-instance-for-empty-row: true
    callSettersOnNulls: true
  mapper-locations: classpath:mapper/*.xml