# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  #context-path: /springboot

# 日志配置
logging:
  file:
    path: /var/danastudio/log
    max-history: 15

# rsa 配置
rsa:
  enabled: true
  public-key: sad


datasource-list: druid
# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.facebook.presto.jdbc.PrestoDriver
    druid:
      url:
      username:
      password:

      # 连接池配置
      initial-size: 5
      max-active: 100
      min-idle: 1
      max-wait: 10
      use-unfair-lock: false
      filters: stat,wall,config
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin

#      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
#      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
#      test-on-borrow: false
#      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
#      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
#      test-while-idle: true
#      # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
#      #validationQuery参数必须设置为非空字符串
#      test-on-return: false
#      # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
#      #如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
#      validation-query: select 1





##########################  mybatis   ##########################
mybatis:
  mapper-locations: classpath:mapper/*.xml